services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lifemanager-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      SQLITE_DB_URL: "jdbc:sqlite:/app/data/db/app.db"
      INIT_SQL_PATH: "file:/app/initdb/init.sql"
      OPENAI_API_KEY: ${OPENAI_API_KEY:-dummy-key}
      APP_API_KEY_NAME: ${APP_API_KEY_NAME:-batch-main}
      APP_API_KEY: ${APP_API_KEY:-}
    volumes:
      - ./data/db:/app/data/db
      - ./docker/initdb/init.sql:/app/initdb/init.sql:ro
    restart: unless-stopped
